### ISSUE TITLE
WGSで実行中EBFilterでエラーが発生することがある

### ISSUE THREAD

**Issue by aokad** [Genomon-Project/GenomonPipeline#110]
そのときのログ
```
/home/w3varann/.local/bin/EBFilter -f anno -q 20 -Q 15 $OUT_SIMPLE_REPEAT ~/work-4/PV_201510071630/mutation/PV1064/PV1064.markdup.12.bam ~/work-4/PV_201510071630/mutation/control_panel/List1.control_panel.txt $OUT_EB || exit $?
+ /home/w3varann/.local/bin/EBFilter -f anno -q 20 -Q 15 ~/work-4/PV_201510071630/mutation/PV1064/PV1064.simplerepeat_mutations.12.txt ~/work-4/PV_201510071630/mutation/PV1064/PV1064.markdup.12.bam ~/work-4/PV_201510071630/mutation/control_panel/List1.control_panel.txt ~/work-4/PV_201510071630/mutation/PV1064/PV1064.ebfilter_mutations.12.txt
/usr/local/package/python2.7/current/lib/python2.7/site-packages/rpy2/robjects/robject.py:5: UserWarning: Error in objects(db.pos, all.names = TRUE) :
   .Internal(ls) 関数に 2 個の引数が渡されましたが、3 個でなくてはなりません

  rpy2.rinterface.initr()
Traceback (most recent call last):
  File "/home/w3varann/.local/bin/EBFilter", line 36, in <module>
    main(args)
  File "/home/w3varann/.local/lib/python2.7/site-packages/ebfilter/run.py", line 158, in main
    EBFilter_worker_anno(targetMutationFile, targetBamPath, controlBamPathList, outputPath, mapping_qual_thres, base_qual_thres)
  File "/home/w3varann/.local/lib/python2.7/site-packages/ebfilter/run.py", line 113, in EBFilter_worker_anno
    F_control = pos2pileup_control[chr + '\t' + pos].split('\t')
KeyError: '7\t76655062'
+ exit 1
```

**Comment by friend1ws** [comment]
多分直したと思う。
