### ISSUE TITLE
STAR+fusionfusion を1160件/projectで実行。OperationalError: database or disk is full

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/GenomonPipeline#112]
ＳＴＡＲ＋fusionfusion を1160件/projectで実行中。
star1160件正常終了、fusionfusion 1042件正常終了。
fusionfusionの残118件をgenomon_pipelineにかけたら
OperationalError: database or disk is full　発生
小分けにして18件指定しても結果は同じ。

ログ全文は以下。
＝＝＝＝＝＝＝＝＝＝＝＝
Traceback (most recent call last):
  File "/sshare4/home_mig/hiroko/WORK/FG_performance/Genomon_ver_2.0.0/genomon_pipeline", line 24, in <module>
    main(args)
  File "/home/w3varann/.local/lib/python2.7/site-packages/genomon_pipeline/run.py", line 47, in main
    multiprocess = 200
  File "/home/w3varann/.local/lib/python2.7/site-packages/ruffus/task.py", line 5503, in pipeline_run
    signal_callback=is_node_up_to_date)
  File "/home/w3varann/.local/lib/python2.7/site-packages/ruffus/graph.py", line 933, in topologically_sorted_nodes
    if not signal_callback(n, extra_data_for_signal):
  File "/home/w3varann/.local/lib/python2.7/site-packages/ruffus/task.py", line 4194, in is_node_up_to_date
    return node._is_up_to_date(extra_data)
  File "/home/w3varann/.local/lib/python2.7/site-packages/ruffus/task.py", line 2409, in _is_up_to_date
    raise errt
ruffus.ruffus_exceptions.RethrownJobError:

    Exceptions generating parameters for

    task = 'genomon_pipeline.rna_pipeline.link_input_fastq'

Original exception:

    Exception #1
      'sqlite3.OperationalError(database or disk is full)' raised in ...
       Task = def genomon_pipeline.rna_pipeline.link_input_fastq(...):

    Traceback (most recent call last):
      File "/home/w3varann/.local/lib/python2.7/site-packages/ruffus/task.py", line 2358, in _is_up_to_date
        verbose_abbreviated_path=verbose_abbreviated_path)
      File "/home/w3varann/.local/lib/python2.7/site-packages/ruffus/file_name_parameters.py", line 534, in needs_update_check_modify_time
        if os.path.relpath(p) not in job_history and p not in set_incomplete_files:
      File "/usr/local/package/python2.7/current/lib/python2.7/_abcoll.py", line 388, in __contains__
        self[key]
      File "/home/w3varann/.local/lib/python2.7/site-packages/ruffus/dbdict.py", line 174, in __getitem__
        (key, )).fetchone()
    OperationalError: database or disk is full

**Comment by roko-t** [comment]
以下に対応例あり。
http://stackoverflow.com/questions/16685016/sqlite3-operationalerror-database-or-disk-is-full-on-lustre

＝＝＝＝＝＝＝＝
an SQLite database actually can get full even if there's plenty of disk space, because it has a limit for the number of pages in a database file:

http://www.sqlite.org/pragma.html#pragma_max_page_count

In my case the value was 1073741823, which meant that in combination with a page size of 1024 Bytes the database maxed out at 1 TB and returned the "database or disk is full" error.

The good news is that you can raise the limit; for example double it by issuing PRAGMA max_page_count = 2147483646;.

The limit doesn't seem to be saved in the database file, though, so you have to run it in your application every time you open the database.

**Comment by roko-t** [comment]
samtools で1件GEのメモリオーバーが出ていたのが原因でした。
その結果が出た1件が再実行の対象の中にあると、他の対象サンプルを実行することなく
即、OperationalError: database or disk is full　で終了する。

**Comment by roko-t** [comment]
OperationalError: database or disk is full　　を生じさせたサンプルを除いて再実行しても
同エラー文言を表示して即終了。
残件を再実行するにはプロジェクトディレクトリを削除して再実行するしかない。
