### ISSUE TITLE
TCGA PAADサンプルでsv_filter でエラー

### ISSUE THREAD

**Issue by aokad** [Genomon-Project/GenomonPipeline#130]
```
11/17/2015 18:09:13: filtering by # of breakpoint containing read pairs and variant sizes
11/17/2015 18:09:21: filtering by nonmatched control panel
11/17/2015 18:09:22: incorporating improperly alinged read pair infomation
11/17/2015 18:09:24: filtering by sizes of covered regions, mapping quality and # of support read pairs
11/17/2015 18:09:24: filtering too close candidates
11/17/2015 18:09:24: performing realignments
sequence depth exceeds the threshould for: 1,144916537,-,1,144916658,-
sequence depth exceeds the threshould for: 1,161475704,-,1,161475794,-
finished checking 100 candidates
sequence depth exceeds the threshould for: 10,30128424,-,14,51219314,+
finished checking 200 candidates
finished checking 300 candidates
Traceback (most recent call last):
  File "/home/w3varann/.local/bin/GenomonSV", line 67, in <module>
    args.func(args)
  File "/home/w3varann/.local/lib/python2.7/site-packages/genomonsv/run.py", line 190, in genomonSV_filt
    paramConf["realignment_validation_condition"])
  File "/home/w3varann/.local/lib/python2.7/site-packages/genomonsv/filterFunction.py", line 393, in validateByRealignment
    tumorRef, tumorAlt = realignmentFunction.summarizeRefAlt(outputFilePath + ".tmp.tumor.psl", STDFlag)
  File "/home/w3varann/.local/lib/python2.7/site-packages/genomonsv/realignmentFunction.py", line 395, in summarizeRefAlt
    tpos = int(F[15])
IndexError: list index out of range
```

**Comment by friend1ws** [comment]
対象の検体のlog fileをください。

**Comment by ken0-1n** [comment]
スパコンの調子が悪いため、偶然のエラーかと思われる。closeする。
