### ISSUE TITLE
mutation_callでrealignment_mutations.1.txt.tmp.refalt.faの Input/output error

### ISSUE THREAD

**Issue by aokad** [Genomon-Project/GenomonPipeline#135]
今回はtumorの重複とsingleリードはありません。

ログはここにあります。
`/sshare3/home/aiokada/work/test2/log/mutation_call_20151124_1317_777238.sh.e5238074.1`

`/sshare3/home/aiokada/work/test2/log/mutation_call_20151124_1317_577420.sh.*` も失敗しているがこちらはqreport で, ext=0, fail=25

以下はエラーログの最後

```
+ /home/w3varann/.local/bin/mutfilter realignment --tumor_min_mismatch 0 --normal_max_mismatch 100000 --score_difference 5 --window_size 200 --max_depth 5000 --target_mutation_file /sshare3/home/aiokada/work/test2/mutation/TCGA-AB-2829-03/TCGA-AB-2829-03.fisher_mutations.1.txt -1 /sshare3/home/aiokada/work/test2/bam/TCGA-AB-2829-03/TCGA-AB-2829-03.markdup.bam -2 /sshare3/home/aiokada/work/test2/bam/TCGA-AB-2829-11/TCGA-AB-2829-11.markdup.bam --output /sshare3/home/aiokada/work/test2/mutation/TCGA-AB-2829-03/TCGA-AB-2829-03.realignment_mutations.1.txt --ref_genome /home/w3varann/database/GRCh37/GRCh37.fa --blat_path /home/w3varann/tools/blat_x86_64/blat
Traceback (most recent call last):
  File "/home/w3varann/.local/bin/mutfilter", line 74, in <module>
    args.func(args)
  File "/home/w3varann/.local/lib/python2.7/site-packages/mutfilter/run.py", line 21, in run_realignment_filter
    realignf.filter(arg.bam1, arg.bam2, arg.output, arg.target_mutation_file)
  File "/home/w3varann/.local/lib/python2.7/site-packages/mutfilter/realignment_filter.py", line 275, in filter
    self.makeTwoReference(chr,start,end,ref,alt,output + ".tmp.refalt.fa")
  File "/home/w3varann/.local/lib/python2.7/site-packages/mutfilter/realignment_filter.py", line 149, in makeTwoReference
    hOUT = open(output, 'w')
IOError: [Errno 5] Input/output error: '/sshare3/home/aiokada/work/test2/mutation/TCGA-AB-2829-03/TCGA-AB-2829-03.realignment_mutations.1.txt.tmp.refalt.fa'
+ exit 1
```

genomon　サンプルシートは`/sshare3/home/aiokada/work/test2/sample_import.csv`

**Comment by aokad** [comment]
【追記】
異常終了後、working dirを触らずに、再度実行したところ再現しない。
生成物を削除して再現するか、確認中。
