### ISSUE TITLE
active_HGMD_flagの有無をチェックする

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonPipeline#147]
改善した方が良い。異常終了するとログが出力される。
try:
    active_HGMD_flag = task_conf.get("annotation", "active_HGMD_flag")
    HGMD_tabix_db = genomon_conf.get("REFERENCE", "HGMD_tabix_db")
except ConfigParser.NoOptionError:
    print "assumed cause: [HGMD] is not defined"

**Comment by ken0-1n** [comment]
正常終了するときは問題ないが、異常終了した時にactive_HGMD_flagには問題がないのにStackTraceが出力されてしまう

Traceback (most recent call last):
----------
  File "/home/sepon/.local/lib/python2.7/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/home/sepon/.local/lib/python2.7/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/home/sepon/.local/lib/python2.7/site-packages/genomon_pipeline/dna_pipeline.py", line 403, in identify_mutations
    mutation_call.task_exec(arguments, run_conf.project_root + '/log', run_conf.project_root + '/script', max_task_id)
  File "/home/sepon/.local/lib/python2.7/site-packages/genomon_pipeline/dna_pipeline.py", line 333, in identify_mutations
    active_HGMD_flag = task_conf.get("annotation", "active_HGMD_flag")
  File "/usr/local/package/python2.7/current/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'active_hgmd_flag' in section: 'annotation'
