### ISSUE TITLE
genomon.py　のオプション--jobs を設定しないとerror: can't start new thread

### ISSUE THREAD

**Issue by roko-t** [Genomon-Project/GenomonPipeline#63]
```
 /usr/local/package/python2.7/current/bin/python /home/w3varann/tools/Genomon/genomon.py --config_file /home/w3varann/tools/Genomon/samples/genomon.cfg --job_file config/CD274_RNA_150731_job_20150805_star.yaml --param_file config/CD274_RNA_150731_param_star_limitBAMsortRAM_31GB.yaml --verbose 1 --drmaa --use_threads

Generated by /home/w3varann/tools/Genomon/genomon.py
    Input config file = /home/w3varann/tools/Genomon/samples/genomon.cfg
    Input job file    = config/CD274_RNA_150731_job_20150805_star.yaml
    RunTask: run_mode=DRMAA
    main: Unexpected error
    <class 'thread.error'>: genomon.py:487
Process LoggingManager-1:
Traceback (most recent call last):
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/managers.py", line 558, in _run_server
    server.serve_forever()
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/managers.py", line 184, in serve_forever
    t.start()
  File "/usr/local/package/python2.7/current/lib/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
Process SyncManager-2:
Traceback (most recent call last):
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/managers.py", line 558, in _run_server
    server.serve_forever()
  File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/managers.py", line 184, in serve_forever
    t.start()
  File "/usr/local/package/python2.7/current/lib/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

```

**Comment by eigoshimizu** [comment]
現在の仕様としては、

--jobs を指定しない場合は、投入されるサンプル数で、並列化します。
ruffus が並列化するときに、あらかじめ並列数だけリソースを確保するようです。
投入するサンプル数によっては、並列数のリソースを確保する時点で、 qlogin のメモリーを全て使用してしまい、エラーになるものと思われます。

解決方法としては、 
qlogin のデフォルトのメモリー量 5.3G で確保できる並列数を調べて、
--jobs が指定していない場合は、5.3Gで確保できる並列数にしてしまうことで、並列数は少なくても、落ちずに実行できます。
わかっているユーザーは、qloginでの指定メモリー量によって、 --jobs の値を指定し、並列数を増やして頂くような感じにします。

ご意見を伺いたいのですが、どうでしょうか？
